### ISSUE TITLE
BUG: Center Tile Should Score as Double Word

### ISSUE THREAD

**Issue by groundh0g** [groundh0g/games.joehall.net#3]
## Overview

The word bonus and letter bonus do not seem to be applied.

## Tasks

- [ ] Ensure the word bonus is applied when scoring the first placed word.
- [ ] Ensure word bonuses are applied in general.
- [ ] Ensure tile bonuses are applied.

## Tech Notes

Note that the word "JADED" is scored at 15 points, but should have been scored at 30 since the first "D" was played on the center tile.

![Image](https://user-images.githubusercontent.com/5958942/265279353-679ed4e1-5aa5-42c7-8cd2-2bb4da0e4a94.png)

Note that the word "GROUT" is scored at 8 points, but should have been scored at 32? since the "G" was played on the "DW" tile and "T" was played on the center tile, which is a double-word bonus as well.

![Image](https://github.com/groundh0g/games.joehall.net/assets/5958942/06db1a66-7322-420a-a41a-74fe9633aa83)
